export const typeToName = {
    "AttackPercent": "Attack%",
    "CriticalHitChancePercent": "Critical Hit Chance",
    "CriticalHitDamagePercent": "Critical Hit Damage",
    "DefensePercent": "Defense%",
    "EffectivenessPercent": "Effectiveness",
    "EffectResistancePercent": "Effect Resistance",
    "HealthPercent": "Health%",
    "Speed": "Speed",
    "Attack": "Attack",
    "Defense": "Defense",
    "Health": "Health",
};

export const nameToType = {
    "Attack%": "AttackPercent",
    "Critical Hit Chance": "CriticalHitChancePercent",
    "Critical Hit Damage": "CriticalHitDamagePercent",
    "Defense%": "DefensePercent",
    "Effectiveness": "EffectivenessPercent",
    "Effect Resistance": "EffectResistancePercent",
    "Health%": "HealthPercent",
    "Speed": "Speed",
    "Attack": "Attack",
    "Defense": "Defense",
    "Health": "Health",
};

export const nameBySetByGear = {
    Weapon: {
        HealthSet: "Dark Steel Saber",
        DefenseSet: "Dark Steel Saber",
        AttackSet: "Dark Steel Saber",
        ProtectionSet: "Dark Steel Saber",
        SpeedSet: "Abyss Drake Bonesword",
        CriticalSet: "Abyss Drake Bonesword",
        HitSet: "Abyss Drake Bonesword",
        DestructionSet: "Hellish Essence Orb",
        LifestealSet: "Hellish Essence Orb",
        CounterSet: "Hellish Essence Orb",
        ResistSet: "Hellish Essence Orb",
        UnitySet: "Indomitable Spider Mace",
        RageSet: "Indomitable Spider Mace",
        ImmunitySet: "Indomitable Spider Mace",
        RevengeSet: "Demons Cursed Double Edged Sword",
        InjurySet: "Demons Cursed Double Edged Sword",
        PenetrationSet: "Demons Cursed Double Edged Sword",
        TorrentSet: "Demons Cursed Double Edged Sword",
    },
    Helmet: {
        HealthSet: "Dark Steel Helm",
        DefenseSet: "Dark Steel Helm",
        AttackSet: "Dark Steel Helm",
        ProtectionSet: "Dark Steel Helm",
        SpeedSet: "Abyss Drake Mask",
        CriticalSet: "Abyss Drake Mask",
        HitSet: "Abyss Drake Mask",
        DestructionSet: "Hellish Essence Crown",
        LifestealSet: "Hellish Essence Crown",
        CounterSet: "Hellish Essence Crown",
        ResistSet: "Hellish Essence Crown",
        UnitySet: "Indomitable Spider Helm",
        RageSet: "Indomitable Spider Helm",
        ImmunitySet: "Indomitable Spider Helm",
        RevengeSet: "Demon's Cursed Horned Helm",
        InjurySet: "Demon's Cursed Horned Helm",
        PenetrationSet: "Demon's Cursed Horned Helm",
        TorrentSet: "Demon's Cursed Horned Helm",
    },
    Armor: {
        HealthSet: "Dark Steel Armor",
        DefenseSet: "Dark Steel Armor",
        AttackSet: "Dark Steel Armor",
        ProtectionSet: "Dark Steel Armor",
        SpeedSet: "Abyss Drake Hide Tunic",
        CriticalSet: "Abyss Drake Hide Tunic",
        HitSet: "Abyss Drake Hide Tunic",
        DestructionSet: "Hellish Essence Robe",
        LifestealSet: "Hellish Essence Robe",
        CounterSet: "Hellish Essence Robe",
        ResistSet: "Hellish Essence Robe",
        UnitySet: "Indomitable Spider Breastplate",
        RageSet: "Indomitable Spider Breastplate",
        ImmunitySet: "Indomitable Spider Breastplate",
        RevengeSet: "Demons Cursed Heavy Armor",
        InjurySet: "Demons Cursed Heavy Armor",
        PenetrationSet: "Demons Cursed Heavy Armor",
        TorrentSet: "Demons Cursed Heavy Armor",
    },
    Necklace: {
        HealthSet: "Dark Steel Warmer",
        DefenseSet: "Dark Steel Warmer",
        AttackSet: "Dark Steel Warmer",
        ProtectionSet: "Dark Steel Warmer",
        SpeedSet: "Abyss Blade Necklace",
        CriticalSet: "Abyss Blade Necklace",
        HitSet: "Abyss Blade Necklace",
        DestructionSet: "Obsidian Amulet",
        LifestealSet: "Obsidian Amulet",
        CounterSet: "Obsidian Amulet",
        ResistSet: "Obsidian Amulet",
        UnitySet: "Indomitable Spider Pendant",
        RageSet: "Indomitable Spider Pendant",
        ImmunitySet: "Indomitable Spider Pendant",
        RevengeSet: "Demons Cursed Necklace",
        InjurySet: "Demons Cursed Necklace",
        PenetrationSet: "Demons Cursed Necklace",
        TorrentSet: "Demons Cursed Necklace",
    },
    Ring: {
        HealthSet: "Dark Steel Gauntlet",
        DefenseSet: "Dark Steel Gauntlet",
        AttackSet: "Dark Steel Gauntlet",
        ProtectionSet: "Dark Steel Gauntlet",
        SpeedSet: "Awakened Dragon Gem",
        CriticalSet: "Awakened Dragon Gem",
        HitSet: "Awakened Dragon Gem",
        DestructionSet: "Obsidian Ring",
        LifestealSet: "Obsidian Ring",
        CounterSet: "Obsidian Ring",
        ResistSet: "Obsidian Ring",
        UnitySet: "Indomitable Spider Ring",
        RageSet: "Indomitable Spider Ring",
        ImmunitySet: "Indomitable Spider Ring",
        RevengeSet: "Demons Cursed Ring",
        InjurySet: "Demons Cursed Ring",
        PenetrationSet: "Demons Cursed Ring",
        TorrentSet: "Demons Cursed Ring",
    },
    Boots: {
        HealthSet: "Dark Steel Boots",
        DefenseSet: "Dark Steel Boots",
        AttackSet: "Dark Steel Boots",
        ProtectionSet: "Dark Steel Boots",
        SpeedSet: "Abyss Drake Boots",
        CriticalSet: "Abyss Drake Boots",
        HitSet: "Abyss Drake Boots",
        DestructionSet: "Hellish Essence Treads",
        LifestealSet: "Hellish Essence Treads",
        CounterSet: "Hellish Essence Treads",
        ResistSet: "Hellish Essence Treads",
        UnitySet: "Indomitable Spider Boots",
        RageSet: "Indomitable Spider Boots",
        ImmunitySet: "Indomitable Spider Boots",
        RevengeSet: "Demons Cursed Fine Boots",
        InjurySet: "Demons Cursed Fine Boots",
        PenetrationSet: "Demons Cursed Fine Boots",
        TorrentSet: "Demons Cursed Fine Boots",
    }
}

export const conversionNameByGear = {
    Weapon: "Corinoa",
    Helmet: "Elsquare",
    Armor: "Corimescent",
    Necklace: "Corselium",
    Ring: "Seekers Ring",
    Boots: "Practical Boots"
}

export const reforgedNameBySetByGear = {
    Weapon: {
        HealthSet: "Dark Saber",
        DefenseSet: "Dark Saber",
        AttackSet: "Dark Saber",
        ProtectionSet: "Dark Saber",
        SpeedSet: "Ancient Drake Bonesword",
        CriticalSet: "Ancient Drake Bonesword",
        HitSet: "Ancient Drake Bonesword",
        DestructionSet: "Twilight Essence Orb",
        LifestealSet: "Twilight Essence Orb",
        CounterSet: "Twilight Essence Orb",
        ResistSet: "Twilight Essence Orb",
        UnitySet: "Origin Spider Queen's Mace",
        RageSet: "Origin Spider Queen's Mace",
        ImmunitySet: "Origin Spider Queen's Mace",
        RevengeSet: "Dark Soul's Double-Edged Sword",
        InjurySet: "Dark Soul's Double-Edged Sword",
        PenetrationSet: "Dark Soul's Double-Edged Sword",
        TorrentSet: "Dark Soul's Double-Edged Sword",
    },
    Helmet: {
        HealthSet: "Dark Helm",
        DefenseSet: "Dark Helm",
        AttackSet: "Dark Helm",
        ProtectionSet: "Dark Helm",
        SpeedSet: "Ancient Drake Mask",
        CriticalSet: "Ancient Drake Mask",
        HitSet: "Ancient Drake Mask",
        DestructionSet: "Twilight Essence Crown",
        LifestealSet: "Twilight Essence Crown",
        CounterSet: "Twilight Essence Crown",
        ResistSet: "Twilight Essence Crown",
        UnitySet: "Queen Origin Spider's Helm",
        RageSet: "Queen Origin Spider's Helm",
        ImmunitySet: "Queen Origin Spider's Helm",
        RevengeSet: "Dark Soul's Horned Helm",
        InjurySet: "Dark Soul's Horned Helm",
        PenetrationSet: "Dark Soul's Horned Helm",
        TorrentSet: "Dark Soul's Horned Helm",
    },
    Armor: {
        HealthSet: "Dark Armor",
        DefenseSet: "Dark Armor",
        AttackSet: "Dark Armor",
        ProtectionSet: "Dark Armor",
        SpeedSet: "Ancient Drake Leather Tunic",
        CriticalSet: "Ancient Drake Leather Tunic",
        HitSet: "Ancient Drake Leather Tunic",
        DestructionSet: "Twilight Essence Robe",
        LifestealSet: "Twilight Essence Robe",
        CounterSet: "Twilight Essence Robe",
        ResistSet: "Twilight Essence Robe",
        UnitySet: "Origin Spider Queen's Breastplate",
        RageSet: "Origin Spider Queen's Breastplate",
        ImmunitySet: "Origin Spider Queen's Breastplate",
        RevengeSet: "Dark Soul's Heavy Armor",
        InjurySet: "Dark Soul's Heavy Armor",
        PenetrationSet: "Dark Soul's Heavy Armor",
        TorrentSet: "Dark Soul's Heavy Armor",
    },
    Necklace: {
        HealthSet: "Dark Warmer",
        DefenseSet: "Dark Warmer",
        AttackSet: "Dark Warmer",
        ProtectionSet: "Dark Warmer",
        SpeedSet: "Dark Abyss Necklace",
        CriticalSet: "Dark Abyss Necklace",
        HitSet: "Dark Abyss Necklace",
        DestructionSet: "Bloodstone Amulet",
        LifestealSet: "Bloodstone Amulet",
        CounterSet: "Bloodstone Amulet",
        ResistSet: "Bloodstone Amulet",
        UnitySet: "Origin Spider Queen's Pendant",
        RageSet: "Origin Spider Queen's Pendant",
        ImmunitySet: "Origin Spider Queen's Pendant",
        RevengeSet: "Dark Soul's Necklace",
        InjurySet: "Dark Soul's Necklace",
        PenetrationSet: "Dark Soul's Necklace",
        TorrentSet: "Dark Soul's Necklace",
    },
    Ring: {
        HealthSet: "Dark Gauntlet",
        DefenseSet: "Dark Gauntlet",
        AttackSet: "Dark Gauntlet",
        ProtectionSet: "Dark Gauntlet",
        SpeedSet: "Dark Red Dragon Gem",
        CriticalSet: "Dark Red Dragon Gem",
        HitSet: "Dark Red Dragon Gem",
        DestructionSet: "Bloodstone Ring",
        LifestealSet: "Bloodstone Ring",
        CounterSet: "Bloodstone Ring",
        ResistSet: "Bloodstone Ring",
        UnitySet: "Origin Spider Queen's Ring",
        RageSet: "Origin Spider Queen's Ring",
        ImmunitySet: "Origin Spider Queen's Ring",
        RevengeSet: "Dark Soul's Ring",
        InjurySet: "Dark Soul's Necklace",
        PenetrationSet: "Dark Soul's Necklace",
        TorrentSet: "Dark Soul's Necklace",
    },
    Boots: {
        HealthSet: "Dark Boots",
        DefenseSet: "Dark Boots",
        AttackSet: "Dark Boots",
        ProtectionSet: "Dark Boots",
        SpeedSet: "Ancient Drake Boots",
        CriticalSet: "Ancient Drake Boots",
        HitSet: "Ancient Drake Boots",
        DestructionSet: "Twilight Essence Treads",
        LifestealSet: "Twilight Essence Treads",
        CounterSet: "Twilight Essence Treads",
        ResistSet: "Twilight Essence Treads",
        UnitySet: "Origin Spider Queen's Boots",
        RageSet: "Origin Spider Queen's Boots",
        ImmunitySet: "Origin Spider Queen's Boots",
        RevengeSet: "Dark Soul's Fine Boots",
        InjurySet: "Dark Soul's Fine Boots",
        PenetrationSet: "Dark Soul's Fine Boots",
        TorrentSet: "Dark Soul's Fine Boots",
    }
}