import style from "./footer.style";

const Footer = () => {
	return (
		<div css={style.footer}>
			<div css={style.section}>{`© 2023 Epic Seven Toolkit`}</div>
			<div css={style.section}>
				<span>
					{`This website is an unofficial fan site created by DuDuSteo. It is not affiliated with or endorsed by Smilegate Megaport, the developers of "Epic Seven."`}
				</span>
				<span>
					{`The content on this site is generated by fans for the purpose of discussing and celebrating the game.`}
				</span>
			</div>
			<div css={style.section}>
				<span>{`Special thanks to:`}</span>
				<span>
					{` nORbDragon - for giving me the access to datamined spine L2Ds: `}
					<a href="https://www.e7vau.lt/">https://www.e7vau.lt/</a>
				</span>
				<span>
					{` fribbels - for helping me with the Epic Seven notations and making a great tools for whole community: `}
					<a href="https://fribbels.github.io/e7/hero-library.html">
						https://fribbels.github.io/e7/hero-library.html
					</a>
				</span>
			</div>
		</div>
	);
};

export default Footer;
